server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Roteamento do React 
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy Reverso para os Controllers do Backend 
    location /auth {
        proxy_pass http://backend:8080/auth;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /tasks {
        proxy_pass http://backend:8080/tasks;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}