spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/task_manager
    username: admin
    password: SENHA_SQL
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG