spring:
  application:
    name: task-manager
  datasource:
    url: jdbc:postgresql://localhost:5433/task_manager?stringtype=unspecified
    username: admin
    password: SENHA_SQL
  jpa:
    hibernate:
      ddl-auto: validate
api:
  security:
    token:
      secret: ${JWT_Secret:SenhaTokenSuperSecreta}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method